import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { ResearchResponse } from '../api/contract'
import { bootstrap } from '../testing/fixtures'

const aiResearch = vi.fn<(req: unknown) => Promise<ResearchResponse>>()
vi.mock('../api/ai', () => ({
  aiClassify: vi.fn(), aiCopilot: vi.fn(), aiDraft: vi.fn(), aiMeetingRecap: vi.fn(), aiReplySuggest: vi.fn(),
  aiResearch: (req: unknown) => aiResearch(req),
}))

async function load(providers: { anthropic: boolean; xai: boolean }) {
  vi.resetModules()
  const session = await import('../data/session')
  const client = await import('./client')
  const b = bootstrap()
  session.initSession({ ...b, ai: { enabled: providers.anthropic, providers } })
  return client
}

const llm: ResearchResponse = {
  mode: 'llm', provider: 'xai', model: 'grok-4.7', generated: true, crmFactsUsed: [],
  inference: {
    overview: 'o', businessModel: 'b', challenges: [], offerings: [], stakeholders: [], angle: 'a',
    sources: [{ title: 'Acme', url: 'https://acme.test/about' }], disclaimer: 'Generated by AI (Grok) from CRM data plus live web and X search.',
  },
}

beforeEach(() => { aiResearch.mockReset() })

describe('per-provider "not configured"', () => {
  it('reports each provider from its own flag', async () => {
    const onlyClaude = await load({ anthropic: true, xai: false })
    expect(onlyClaude.aiNotConfigured()).toBe(false)
    expect(onlyClaude.aiNotConfigured('xai')).toBe(true)
    const onlyGrok = await load({ anthropic: false, xai: true })
    expect(onlyGrok.aiNotConfigured()).toBe(true)
    expect(onlyGrok.aiNotConfigured('xai')).toBe(false)
  })
})

describe('badgeText', () => {
  it('names the provider that wrote the text', async () => {
    const c = await load({ anthropic: true, xai: true })
    expect(c.badgeText({ source: 'llm', model: 'grok-4.7', provider: 'xai' })).toBe('AI-written by Grok (grok-4.7)')
    expect(c.badgeText({ source: 'llm', model: 'claude-sonnet-4-6', provider: 'anthropic' })).toBe('AI-written by Claude (claude-sonnet-4-6)')
    expect(c.badgeText({ source: 'stub', model: null, provider: 'xai', label: 'Grok is not configured' })).toBe('Grok is not configured')
  })
})

describe('research', () => {
  it('keeps the provider, model and web sources on the record and tags the result', async () => {
    const c = await load({ anthropic: true, xai: true })
    aiResearch.mockResolvedValueOnce(llm)
    const out = await c.research(null, 'ard', { name: 'Newco' })
    expect(out.ai).toMatchObject({ source: 'llm', provider: 'xai', model: 'grok-4.7' })
    expect(out.value).toMatchObject({
      provider: 'xai', providerModel: 'grok-4.7', webSources: [{ title: 'Acme', url: 'https://acme.test/about' }],
      inferred: [llm.inference?.disclaimer], simulated: false,
    })
    expect(out.value).toMatchObject({ sources: expect.arrayContaining([expect.objectContaining({ label: 'Grok (grok-4.7)' })]) })
  })

  it('shows the local template with the Grok stub label when the key is missing', async () => {
    const c = await load({ anthropic: true, xai: false })
    aiResearch.mockResolvedValueOnce({ mode: 'stub', provider: 'xai', model: null, generated: false, label: 'Grok is not configured', crmFactsUsed: [] })
    const out = await c.research(null, 'ard', { name: 'Newco' })
    expect(out.ai).toMatchObject({ source: 'stub', provider: 'xai', label: 'Grok is not configured' })
    expect(out.value).toMatchObject({ simulated: true })
  })
})
